export const ProjectsQuery = 'projects'
export const TeamsQuery = 'teams'
export const RolesQuery = 'roles'
export const CurrentUserQuery = 'currentUser'
export const TasksQuery = 'tasks'
export const UsersQuery = 'users'
export const RaportsQuery = 'raports'
export const TEAM_MEMBERS = 'TEAM_MEMBERS'
